---
driver:
  name: rackspace
  public_key_path: ~/.ssh/id_rsa.pub
  rackspace_region: 'IAD'
  flavor_id: 'general1-2'
  # Keep in mind, to use knife-rackspace you'll need to export
  # RACKSPACE_USERNAME and RACKSPACE_API_KEY in your shell

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  data_bags_path: 'test/integration/data_bags'
  encrypted_data_bag_secret_key_path: 'test/integration/encrypted_data_bag_secret'
  client_rb:
    environment: 'kitchen'
  attributes:
    public_info:
      remote_ip: '127.0.0.1'
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    ntp:
      apparmor_enabled: false
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant','kitchen']
        passwordless: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
      omnibus_updater:
        enabled: false
      iptables:
        allow_ssh_from_world: true
    rackspace:
      cloud_credentials:
        username: 'kitchen'
        api_key: 'test_kitchen'
    disk:
      timeout: 10
    testkitchen: true
    mysql:
      server_root_password: 'mysql_test'
      master: '127.0.0.1'
    network:
      interfaces:
        eth1:
          addresses:
            127.0.0.1:
              family: 'inet'

