source 'https://supermarket.chef.io'
metadata

cookbook 'platformstack', git: 'git@github.com:rackspace-cookbooks/platformstack.git'
cookbook 'rackspace_cloudbackup', git: 'git@github.com:rackspace-cookbooks/rackspace_cloudbackup.git'

